### ISSUE TITLE
getCry missing in TS (and other languages)

### ISSUE THREAD

**Issue by StephanSvoboda** [emilybache/Parrot-Refactoring-Kata#43]
Hello Emily,

is there a reason for the difference?

In the last dojo i faciliated that lead to confusion. For TS I happly would provide a PR.

BR
Stephan

**Comment by emilybache** [comment]
The first version of the kata didn't have the 'getCry' method and I havn't got around to adding it to all the language versions. A PR for TS would be most welcome.
